### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by StefanScherer** [DieterReuter/golang-armbuilds#1]
How did you build these releases?
We need golang 1.5.1 as well.

**Comment by DieterReuter** [comment]
Will document the process here soon.

**Comment by Govinda-Fichtner** [comment]
We need 1.5.1 for our next steps... :)

**Comment by DieterReuter** [comment]
Please see #1 for building steps for Go 1.4.x on a Scaleway C1 ARMv7 server, which is the base for building Go 1.5.x.

Feel free to file a PR.
